CREATE TABLE projects (
    id VARCHAR(26) NOT NULL PRIMARY KEY,
    project_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(100) NOT NULL,
    team_id VARCHAR(26) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL
);